package org.example;
import java.sql.*;

public class Conn {
    private static final String URL = System.getenv("DB_URL") != null ? System.getenv("DB_URL") : "jdbc:mysql://localhost:3306/bank_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC";
    private static final String USER = System.getenv("DB_USER") != null ? System.getenv("DB_USER") : "root";
    private static final String PASSWORD = System.getenv("DB_PASSWORD") != null ? System.getenv("DB_PASSWORD") : "4hmRahulop@123";
    public Connection connection;

    public Conn() {
        try {
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
            System.out.println("✅ Database connected successfully!");
        } catch (SQLException e) {
            connection = null;
            System.err.println("❌ Failed to connect to database!");
            e.printStackTrace();
        }
    }

    // Normal prepareStatement
    public PreparedStatement prepareStatement(String query) throws SQLException {
        if (connection == null || connection.isClosed()) {
            throw new SQLException("❌ Cannot prepare statement: No active database connection.");
        }
        return connection.prepareStatement(query);
    }

    // Overloaded prepareStatement for RETURN_GENERATED_KEYS
    public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
        if (connection == null || connection.isClosed()) {
            throw new SQLException("❌ Cannot prepare statement: No active database connection.");
        }
        return connection.prepareStatement(query, autoGeneratedKeys);
    }

    public void close() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
                System.out.println("✅ Database connection closed.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}